[build]
  command = "prisma generate && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.13.0"

[functions]
   directory = ".netlify/edge-functions/"
  external_node_modules = ["@prisma/client", "prisma"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/server"
  status = 200
  force = true